AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'db/**'
    - 'bin/**'
    - 'config/**/*'
    - 'spec/**/mocked_params.rb'


###############
# Bundler
###############

Bundler/OrderedGems:
  Enabled: false

###############
# Gemspec
###############

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

###############
# Layout
###############

Layout/AccessModifierIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/AssignmentIndentation:
  Enabled: false

Layout/BeginEndAlignment:
  Enabled: false

Layout/BlockAlignment:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ConditionPosition:
  Enabled: false

Layout/DefEndAlignment:
  Enabled: false

Layout/DotPosition:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EndAlignment:
  Enabled: false
  EnforcedStyleAlignWith: variable

Layout/EndOfLine:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstArgumentIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationStyle:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LeadingEmptyLines:
  Enabled: false

Layout/LineLength:
  Enabled: false
  Max: 120
  IgnoredPatterns:
    - '(\A|\s)#' # Don't get upset at comments longer than the line length.
    - 'authorize %' # Exclude Pundit authorization calls
    - 'belongs_to :'
    - 'has_many :'
    - 'has_and_belongs_to_many :'
    - 'has_one :'

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/RescueEnsureAlignment:
  Enabled: false

Layout/SpaceAfterColon:
  Enabled: false

Layout/SpaceAfterComma:
  Enabled: false

Layout/SpaceAfterMethodName:
  Enabled: false

Layout/SpaceAroundKeyword:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceBeforeComma:
  Enabled: false

Layout/SpaceBeforeComment:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

###############
# Lint
###############

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DeprecatedClassMethods:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/DuplicateRegexpCharacterClassElement:
  Enabled: false

Lint/DuplicateRequire:
  Enabled: false

Lint/DuplicateRescueException:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/EmptyConditionalBody:
  Enabled: false

Lint/EmptyFile:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Lint/HashCompareByIdentity:
  Enabled: false

Lint/IdentityComparison:
  Enabled: false

Lint/ImplicitStringConcatenation:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/InterpolationCheck:
  Enabled: false

Lint/LiteralAsCondition:
  Enabled: false

Lint/Loop:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/NoReturnInBeginEndBlocks: 
  Enabled: false

Lint/OutOfRangeRegexpRef:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RaiseException:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/RedundantStringCoercion:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/ReturnInVoidContext:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Lint/ShadowedArgument:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false
  
Lint/SuppressedException:
  Enabled: false

Lint/ToEnumArguments: 
  Enabled: false

Lint/TopLevelReturnWithArgument:
  Enabled: false

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/UnifiedInteger:
  Enabled: false

Lint/UnmodifiedReduceAccumulator: 
  Enabled: false

Lint/UnreachableCode:
  Enabled: false

Lint/UnreachableLoop:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false

Lint/UselessTimes:
  Enabled: false

Lint/Void:
  Enabled: false

###############
# Metrics
###############

Metrics/AbcSize:
  Enabled: false

# Don't complain about long block lengths.
Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  CountComments: false # count full line comments?
  Max: 150
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# Allow for larger methods within reason
Metrics/MethodLength:
  Enabled: false
  Max: 20

Metrics/ModuleLength:
  Enabled: false
  CountComments: false # count full line comments?
  Max: 150

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

###############
# Migration
###############

Migration/DepartmentName:
  Enabled: false

###############
# Naming
###############

Naming/AccessorMethodName:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
  
# All business rules use methods like is_eligible? and has_privilege?
# which is not worth the refactor here, so let's exclude files ending in _rule.rb
Naming/PredicateName:
  Enabled: false
  Exclude:
    - '**/**/*_rule.rb'

Naming/RescuedExceptionsVariableName:
  Enabled: false
  
Naming/VariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

###############
# Security
###############

Security/Eval:
  Enabled: false

Security/Open:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

###############
# Style
###############

Style/AccessModifierDeclarations:
  Enabled: false

# Allow use of multiline curly brace blocks in specs (e.g. `expect {}.to` or `let(:foo) {}`)
Style/AccessorGrouping:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AndOr:
  # Whether `and` and `or` are banned only in conditionals (conditionals)
  # or completely (always).
  EnforcedStyle: always
  Enabled: false
  
Style/ArgumentsForwarding: 
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BisectedAttrAccessor:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false
  
Style/ClassEqualityComparison:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CollectionCompact: 
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition: 
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EmptyLambdaParameter:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Style/ExponentialNotation:
  Enabled: false
  
Style/FloatDivision:
  Enabled: false

Style/For:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

# Don't require the magic comment for Ruby 2.3
Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/Lambda:
  Enabled: false
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/MultipleComparison:
  Enabled: false
  
Style/MutableConstant:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedIfElseCondition: 
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NilLambda:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RandomWithOffset:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantCapitalW:
  Enabled: false

Style/RedundantCondition:
  Enabled: false

Style/RedundantConditional:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantFileExtensionInRequire:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
  
Style/RedundantSelfAssignment:
  Enabled: false

Style/RedundantSort:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/Sample:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/SwapValues: 
  Enabled: false
  
Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false